config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :notes
  root to: "pages#home"
  post "/notes/update_note", to: "notes#update_note", as: "update_note"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
# typed: false
class Note < ApplicationRecord

  before_save :validate_note_subject_max
  before_save :validate_note_body_max
  before_save :ensure_not_blank
  before_save :ensure_title

  belongs_to :user

  private

  def validate_note_subject_max
    raise ActiveRecord::RecordInvalid.new(self), 'Subject is more than 30 characters' if subject.length > 30
  end

  def validate_note_body_max
    raise ActiveRecord::RecordInvalid.new(self), 'Body is more than 1000 characters' if body.length > 1000
  end

  def ensure_not_blank
    raise ActiveRecord::RecordInvalid.new(self), 'Note cannot be blank' if subject == '' && body == ''
  end

  def ensure_title
    self.subject = body[0..29] if subject == ''
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
  validates_uniqueness_of :email, :case_sensitive => false

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:edit, keys: [:name])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    unless current_user
      redirect_to root_path
      flash[:alert] = 'Please Sign in to create note'
    end
    @new_note = Note.new(user_id: current_user.id)
  end

  def create
    new_note = Note.new(note_params)
    if new_note.save!
      flash[:success] = 'Successfully Created Note'
    else
      flash[:alert] = 'Unable to save note. Please try again'
    end
    redirect_to root_path
  rescue ActiveRecord::RecordInvalid => e
    redirect_to root_path
    flash[:alert] = 'ERROR: ' + e.message
  end

  def update_note
    note = Note.find(params[:id])
    if note
      note.update_attribute(params[:attribute].downcase.to_sym, params[:value])
      render json: {message: 'Note Saved' }, status: 200
    else
      render json: { message: 'Note note saved' }, status: 500
    end
  end

  def destroy
    Note.destroy(params[:id])

    if !Note.find_by(id: params[:id])
      flash[:success] = 'successfully destroyed note'
    else
      flash[:alert] = 'There was a problem deleting your note. Please try again.'
    end
    redirect_to root_path
  end

  private
  def note_params
    params.require(:note).permit(:user_id, :subject, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @user_notes = Note.where(user_id: current_user&.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noterizer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if protect_against_forgery? %>
       <meta name="authenticity-token" id="authenticity-token" content="<%= form_authenticity_token %>" />
    <% end %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
    <style>
    body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
    body {font-size:16px;}
    .w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
    .w3-half img:hover{opacity:1}
    </style>
  </head>

  <body>
    <center>
    <% flash.each do |type, msg| %>
      <div style="color: black;">
        <%= msg %>
      </div>
    <% end %>
    </center>
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
      <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
      <div class="w3-container">
        <h3 class="w3-padding-64"><b>Noterizer</b></h3>
      </div>
      <div class="w3-bar-block">
        <%= link_to "Home", root_path, class: "w3-bar-item w3-button w3-hover-white" %>
        <% if current_user %>
          <%= link_to "Create Note", new_note_path, class: "w3-bar-item w3-button w3-hover-white" %>
          <%= link_to current_user.name, edit_user_registration_path, class: "w3-bar-item w3-button w3-hover-white" %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "w3-bar-item w3-button w3-hover-white" %>
        <% end %>
      </div>
    </nav>
    <!-- Top menu on small screens -->
    <header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
      <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
      <span>Noterizer</span>
    </header>
    <%= yield %>
  </body>
</html>

app/views/notes/new.html.erb
<div class="w3-main" style="margin-left:340px;margin-right:40px">
  <div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-jumbo">New Note for <%= current_user.name %></h1>

    <%= form_for(@new_note) do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :subject, class: "form-control" %>
      <%= f.text_field :subject, class: "form-control" %>
      <%= f.label :body, class: "form-control" %>
      <%= f.text_area :body, class: "form-control" %>
      <%= f.submit "Create Note", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<head>
  <script>
    $(document).ready( function () {
      dataTable()
    });
    </script>
</head>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Header -->
  <div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-jumbo"><b>Notes</b></h1>
    <% if current_user %>
      <h1 class="w3-xxxlarge w3-text-red"><b>Welcome, <%= current_user.name %></b></h1>
    <% else %>
      <h1 class="w3-xxxlarge w3-text-red"><b>Sign in for Notes!</b></h1>
      <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
    <% end %>

    <% if current_user && @user_notes.length > 0 %>
    <h1>Your Notes</h1>
    <table id="notes">
      <thead>
      <tr>
        <th>Subject</th>
        <th>Body</th>
        <th>Created At</th>
        <th>Delete</th>
      </tr>
      <thead>
      <tbody>
        <% @user_notes.each do |n| %>
          <%= form_for(n) do |f| %>
            <tr id="<%= n.id %>">
              <td><%= f.text_field "Subject", value: n.subject, id: "#{n.id.to_s}_subject", class: "note-item" %></td>
              <td><%= f.text_field "Body", value: n.body, id: "#{n.id.to_s}_body", class: "note-item" %></td>
              <td><%= time_ago_in_words(n.created_at) %></td>
              <td><%= link_to 'Destroy',  { action: :destroy, id: n.id, controller: :notes }, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %> </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <% end %>
    <hr style="width:50px;border:5px solid red" class="w3-round">
  </div>

<!-- End page content -->
</div>

<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px"><p class="w3-right">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></p></div>
</body>
</html>